repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Or the latest tag
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500'] # Adjust as needed
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.56.0' # Adjust to your ESLint version
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint-plugin-react
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - eslint-plugin-react-hooks #If using react-hooks.
        files: \.(js|jsx|ts|tsx)$
        args: ['--fix']
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0' # Adjust to your Prettier version
    hooks:
      - id: prettier
  - repo: https://github.com/stylelint/stylelint
    rev: 15.11.0 #adjust to your stylelint version.
    hooks:
      - id: stylelint
        files: \.(css|scss|sass|less)$
        args: ['--fix']